# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_pdwm(object):
    def setupUi(self, mw_pdwm):
        mw_pdwm.setObjectName("mw_pdwm")
        mw_pdwm.resize(943, 649)
        self.centralwidget = QtWidgets.QWidget(mw_pdwm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_appr = QtWidgets.QWidget()
        self.tab_appr.setObjectName("tab_appr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_appr)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t_fonts = QtWidgets.QTableWidget(self.tab_appr)
        self.t_fonts.setObjectName("t_fonts")
        self.t_fonts.setColumnCount(0)
        self.t_fonts.setRowCount(0)
        self.gridLayout_2.addWidget(self.t_fonts, 0, 1, 1, 1)
        self.t_appr = QtWidgets.QTableWidget(self.tab_appr)
        self.t_appr.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_appr.setAutoScroll(False)
        self.t_appr.setObjectName("t_appr")
        self.t_appr.setColumnCount(0)
        self.t_appr.setRowCount(0)
        self.gridLayout_2.addWidget(self.t_appr, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_appr, "")
        self.tab_buttons = QtWidgets.QWidget()
        self.tab_buttons.setObjectName("tab_buttons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_buttons)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.t_buttons = QtWidgets.QTableWidget(self.tab_buttons)
        self.t_buttons.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_buttons.setAutoScroll(False)
        self.t_buttons.setObjectName("t_buttons")
        self.t_buttons.setColumnCount(0)
        self.t_buttons.setRowCount(0)
        self.gridLayout_4.addWidget(self.t_buttons, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_buttons, "")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_keys)
        self.gridLayout_5.setObjectName("gridLayout_5")
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_pdwm(object):
    def setupUi(self, mw_pdwm):
        mw_pdwm.setObjectName("mw_pdwm")
        mw_pdwm.resize(943, 649)
        self.centralwidget = QtWidgets.QWidget(mw_pdwm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_appr = QtWidgets.QWidget()
        self.tab_appr.setObjectName("tab_appr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_appr)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t_fonts = QtWidgets.QTableWidget(self.tab_appr)
        self.t_fonts.setObjectName("t_fonts")
        self.t_fonts.setColumnCount(0)
        self.t_fonts.setRowCount(0)
        self.gridLayout_2.addWidget(self.t_fonts, 0, 1, 1, 1)
        self.t_appr = QtWidgets.QTableWidget(self.tab_appr)
        self.t_appr.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_appr.setAutoScroll(False)
        self.t_appr.setObjectName("t_appr")
        self.t_appr.setColumnCount(0)
        self.t_appr.setRowCount(0)
        self.gridLayout_2.addWidget(self.t_appr, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_appr, "")
        self.tab_buttons = QtWidgets.QWidget()
        self.tab_buttons.setObjectName("tab_buttons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_buttons)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.t_buttons = QtWidgets.QTableWidget(self.tab_buttons)
        self.t_buttons.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_buttons.setAutoScroll(False)
        self.t_buttons.setObjectName("t_buttons")
        self.t_buttons.setColumnCount(0)
        self.t_buttons.setRowCount(0)
        self.gridLayout_4.addWidget(self.t_buttons, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_buttons, "")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_keys)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.t_keys = QtWidgets.QTableWidget(self.tab_keys)
        self.t_keys.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_keys.setAutoScroll(False)
        self.t_keys.setObjectName("t_keys")
        self.t_keys.setColumnCount(0)
        self.t_keys.setRowCount(0)
        self.gridLayout_5.addWidget(self.t_keys, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_keys, "")
        self.tab_rules = QtWidgets.QWidget()
        self.tab_rules.setObjectName("tab_rules")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_rules)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.t_rules = QtWidgets.QTableWidget(self.tab_rules)
        self.t_rules.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t_rules.setAutoScroll(False)
        self.t_rules.setObjectName("t_rules")
        self.t_rules.setColumnCount(0)
        self.t_rules.setRowCount(0)
        self.gridLayout_6.addWidget(self.t_rules, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_rules, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)
        mw_pdwm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mw_pdwm)
        self.statusbar.setObjectName("statusbar")
        mw_pdwm.setStatusBar(self.statusbar)

        self.retranslateUi(mw_pdwm)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw_pdwm)

    def retranslateUi(self, mw_pdwm):
        _translate = QtCore.QCoreApplication.translate
        mw_pdwm.setWindowTitle(_translate("mw_pdwm", "MainWindow"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_appr), _translate("mw_pdwm", "APPR"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_buttons), _translate("mw_pdwm", "BUTTONS"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_keys), _translate("mw_pdwm", "KEYS"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_rules), _translate("mw_pdwm", "RULES"))
